### ISSUE TITLE
Cant deploy docker container with user (UID,GUID) arguments?

### ISSUE THREAD

**Issue by GitJamz** [HenryQW/Awesome-TTRSS#116]
Hi,
I have tried to deploy the container with docker-compose and :
user: "1001:101"
for example.. This works fine with postgres container but the main TTRSS container gets permission denied errors.. As soon as I removed the user argument it works..
But this means the container will run with root privs and is neither practical or good practice security wise.. Is this possible to change?

Thanks!

**Comment by HenryQW** [comment]
Hi,

It uses s6 as the process manager which requires root permission.

https://github.com/just-containers/s6-overlay#notes

Since the container is running in unprivileged mode with no exposure to the host, though I'm no security expert, I don't think there is anything to worry about security-wise. 

Please feel free to correct and PR.

**Comment by MihaMarkic** [comment]
@HenryQW Is this the line from docker-entrypoint.sh that runs tt-rss with unprivileged mode (-u nobody)?

`sudo -E -u nobody php /var/www/update.php --update-schema=force-yes`

**Comment by HenryQW** [comment]
I believe TTRSS won't start with a privileged user.
