### ISSUE TITLE
Error clicking link

### ISSUE THREAD

**Issue by dvoijen** [HenryQW/Awesome-TTRSS#183]
**Describe the bug**
When there is a new article and you click on it than it expands, when clicking again on the link it needs to go to the website,
Instead it show a new page with the following error: {"error":{"code":13,"message":null}}

**Have you googled?**
Yes

**Deployment method**
 - Docker or docker-compose
 - latest

**Deployment environment**
 - OS: QNAP
 - Browser: chrome

**To Reproduce**
1. Click on Article
2. Click on 'the same Article

**Expected behavior**
I expect it goes to the webpage of the article

**Screenshots**
{"error":{"code":13,"message":null}}

**Error logs**
None error in the logs

**Comment by Trottel** [comment]
Looks like v20.09-77faa5d has some issues nad popup dialogs might be broken now because of CSRF-related changes, e.g. when you want to change default password or import OPML.
[https://community.tt-rss.org/t/new-install-getting-error-code-6-message-null-at-opml-import/3802](https://community.tt-rss.org/t/new-install-getting-error-code-6-message-null-at-opml-import/3802)

**Comment by HenryQW** [comment]
This should be reported to ttrss' repo.
