### ISSUE TITLE
[BUG]imagecreatefromstring(): Data is not in a recognized format  GD的版本是不是有问题

### ISSUE THREAD

**Issue by ptsa** [HenryQW/Awesome-TTRSS#266]
E_WARNING (2) | 
lib/jimIcon.php:107 |
 imagecreatefromstring(): Data is not in a recognized format

**Comment by dimon222** [comment]
I wonder if its happening now always for all RSS subscriptions that don't have a favicon.
Not sure what could have impacted since this piece wasn't touched for at least 2 weeks, unless there's something we don't know.

It does however seem that its rather upstream issue as dev clearly was trying to debug this piece 2 weeks ago.
https://git.tt-rss.org/fox/tt-rss/commit/5d0f65358fc233dd3fde24d60cbfc74c846af7a6

**Comment by dimon222** [comment]
Fix is merged in ttrss itself now :)

**Comment by HenryQW** [comment]
This is an upstream issue, so wait for the fix, or switch to a stable build. I will close it now.
