### ISSUE TITLE
[BUG] cache_starred_images 无法缓存图片，且日志报错

### ISSUE THREAD

**Issue by wizcabbit** [HenryQW/Awesome-TTRSS#279]
**Bug 描述**
简洁明了地描述这个 bug。

cache_starred_images 无法缓存图片，且日志报错，错误信息在plugins/cache_starred_images/init.php:77

<img width="911" alt="1" src="https://user-images.githubusercontent.com/7270910/110196991-595cc680-7e83-11eb-984e-9c2905613499.png">

但是git.tt-rss.org/fox/tt-rss中，这部分代码应该已经更新：

<img width="510" alt="2" src="https://user-images.githubusercontent.com/7270910/110196993-6083d480-7e83-11eb-816e-8fffd6faadda.png">

我已经尝试过拉取最新的image，但是没有变化

并非所有图片都会触发这个log，但大部分会

**你谷歌/百度了吗？**
YES

**部署方法**
 - docker-compose

**部署环境**
 - Ubuntu

**复现步骤**
复现该 bug 的详细步骤
打开cache_starred_images

**预期结果**
文章中的图片被正确缓存

**截屏**
如果可以提供截屏将有助于 bug 修复。

**错误日志**
当错误发生时，通过终端执行 `docker logs ttrss --tail 100` 获取日志，并将**相关错误日志**粘贴于此处。

**其他**
任何有助于 bug 修复的信息。

**Comment by dimon222** [comment]
Do u have example of feed when this exception is being thrown after starring? I guess it depends on type of content in feed item.

**Comment by wizcabbit** [comment]
No, it's not caused by feed content, all feeds are same. It caused by GLOB_BRACE，this flag is not available on some non GNU systems

**Comment by HenryQW** [comment]
This is a known issue caused by alpine base image, which uses musl libc rather than a standard GNU one, I thought https://github.com/HenryQW/Awesome-TTRSS/blob/acbd95fb83831158e091514efc1251a3466b6da1/Dockerfile#L105 should have addressed that, but apparently it's still not solved.

https://community.tt-rss.org/t/404-errors-with-cache-starred-images/3633/3
