### ISSUE TITLE
Running on Synology 

### ISSUE THREAD

**Issue by thecontinium** [HenryQW/Awesome-TTRSS#81]
Hi

Is there any experience of running this on a synology disk station ?

The disk station has a local network IP address of `192.168.1.nnn` and I am getting a page with the following after accessing the url `http://192.168.1.nnn:181/`

```
Startup failed

Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade. Please fix errors indicated by the following messages:

Please set SELF_URL_PATH to the correct value detected for your server: http://192.168.1.nnn:181/

You might want to check tt-rss wiki or the forums for more information. Please search the forums before creating new topic for your question.
```
where the environment variable is set up exactly as this.

Any help appreciated.

cheers

**Comment by HenryQW** [comment]
I can’t magically know your configurations remotely and magically help you identify problems if you don’t follow the issue template and provide all the necessary information.

**Comment by HenryQW** [comment]
In fact l, this is a common problem caused by user errors in configuration, so my suggestion is to wipe the compose clean, pull the latest build, read the docs carefully.

**Comment by thecontinium** [comment]
Thanks for the quick reply.

I have ttrss setup outside docker on a Mac so have some experience of running it but only outside docker.

When you say docs do you mean the ttrss documentation ?

Cheers
--
The Continium

On 7 October 2019 at 00:53:45, Henry Wang (notifications@github.com<mailto:notifications@github.com>) wrote:

In fact l, this is a common problem caused by user errors in configuration, so my suggestion is to wipe the compose clean, pull the latest build, read the docs carefully.

**Comment by HenryQW** [comment]
This repo aims to save users from the miserable standalone setup, [the docs](https://ttrss.henry.wang/) has everything you need to get the dockerized version up and running. You can test with docker on mac, which will definitely work perfectly. As I don't have any experience with NAS devices I can't say for sure what's causing the problem.

The issue you are facing, mentioned [so many times](https://github.com/HenryQW/Awesome-TTRSS/issues?q=is%3Aissue+sort%3Aupdated-desc+SELF_URL_PATH+is%3Aclosed) in the issue section (some are not in English sorry for that), were all caused by user config errors. Back then I was trying to reproduce the issue with macOS, windows, ubuntu and my own VPS running debian, **but it only occurred when I purposely misconfig-ed the `SELF_URL_PATH` env**. 

I figure that maybe there is ambiguity in the docs somewhere, so please post the problem in the docs and the solution if you manage to sort this out.

**Comment by thecontinium** [comment]
Thanks. Like you say I too run it perfectly on OS X desktop docker. I like the setup.

I suspect it is something to do with the Implementation of docker on the synology. I will try and track it down and if I get to the bottom of it I will let you know.

Cheers

--
The Continium

On 8 October 2019 at 03:02:39, Henry Wang (notifications@github.com<mailto:notifications@github.com>) wrote:

This repo aims to save users from the miserable standalone setup, the docs<https://ttrss.henry.wang/> has everything you need to get the dockerized version up and running. You can test with docker on mac, which will definitely work perfectly. As I don't have any experience with NAS devices I can't say for sure what's causing the problem.

The issue you are facing, mentioned so many times<https://github.com/HenryQW/Awesome-TTRSS/issues?q=is%3Aissue+sort%3Aupdated-desc+SELF_URL_PATH+is%3Aclosed> in the issue section (some are not in English sorry for that), were all caused by user config errors. Back then I was trying to reproduce the issue with macOS, windows, ubuntu and my own VPS running debian, but it only occurred when I purposely misconfig-ed the SELF_URL_PATH env.

I figure that maybe there is ambiguity in the docs somewhere, so please post the problem in the docs and the solution if you manage to sort this out.
